import type { Component } from 'svelte'
import {
  Anchor,
  Archive,
  ArrowLeft,
  Axe,
  BadgeCheck,
  Ban,
  Bandage,
  Bed,
  Beer,
  Bell,
  Bike,
  Box,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Check,
  ChevronRight,
  CircleDot,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crosshair,
  DoorOpen,
  Dot,
  Eye,
  EyeOff,
  Factory,
  Fish,
  Flag,
  Flame,
  Focus,
  Fuel,
  Ghost,
  Gift,
  Hammer,
  Hand,
  Handshake,
  Heart,
  Home,
  Info,
  Key,
  Link,
  Locate,
  Lock,
  LogIn,
  LogOut,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Moon,
  MousePointer,
  Music,
  Navigation,
  Package,
  Phone,
  Pill,
  Plane,
  Plus,
  Pointer,
  Power,
  Radio,
  RefreshCw,
  RotateCcw,
  Scan,
  Scissors,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Siren,
  Skull,
  Sparkles,
  Star,
  Store,
  Sun,
  Syringe,
  Target,
  Trash2,
  TreePine,
  Truck,
  Unlock,
  User,
  UserMinus,
  UserPlus,
  Users,
  Utensils,
  Volume2,
  Wallet,
  Warehouse,
  Wrench,
  X,
  Zap,
} from '@lucide/svelte'

/**
 * The icons an option or the reticle may name, by their lucide name. A
 * curated set rather than the whole library, so the build stays small;
 * an unknown name draws nothing.
 */
export const ICONS: Record<string, Component> = {
  anchor: Anchor,
  archive: Archive,
  'arrow-left': ArrowLeft,
  axe: Axe,
  'badge-check': BadgeCheck,
  ban: Ban,
  bandage: Bandage,
  bed: Bed,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  box: Box,
  briefcase: Briefcase,
  'building-2': Building2,
  bus: Bus,
  camera: Camera,
  car: Car,
  check: Check,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  clock: Clock,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  'credit-card': CreditCard,
  crosshair: Crosshair,
  'door-open': DoorOpen,
  dot: Dot,
  eye: Eye,
  'eye-off': EyeOff,
  factory: Factory,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  focus: Focus,
  fuel: Fuel,
  ghost: Ghost,
  gift: Gift,
  hammer: Hammer,
  hand: Hand,
  handshake: Handshake,
  heart: Heart,
  home: Home,
  info: Info,
  key: Key,
  link: Link,
  locate: Locate,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  mic: Mic,
  moon: Moon,
  'mouse-pointer': MousePointer,
  music: Music,
  navigation: Navigation,
  package: Package,
  phone: Phone,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  pointer: Pointer,
  power: Power,
  radio: Radio,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  ship: Ship,
  'shopping-cart': ShoppingCart,
  siren: Siren,
  skull: Skull,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  'trash-2': Trash2,
  'tree-pine': TreePine,
  truck: Truck,
  unlock: Unlock,
  user: User,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  utensils: Utensils,
  'volume-2': Volume2,
  wallet: Wallet,
  warehouse: Warehouse,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

/** The component behind an icon name, or null when the name is unknown. */
export const iconOf = (name: string | undefined): Component | null =>
  name ? (ICONS[name] ?? null) : null
